version: "3.7"
services:
  postgresdb:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/tmp
    volumes:
      - ./database/data:/var/lib/postgresql/data/
      - ./database/init.sql:/docker-entrypoint-initdb.d/1-init.sql
  backend:
    build: 
      context: backend
      dockerfile: Dockerfile
    links:
      - postgresdb
    volumes:
      - ./:/usr/src/app
    ports:
      - "5000:5000"