version: "3.7"
services:
  postgresdb:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/tmp
    volumes:
      - ./database/data:/var/lib/postgresql/data/
      - ./database/init.sql:/docker-entrypoint-initdb.d/1-init.sql
    ports:
      - "34532:5432"
    restart: unless-stopped
  dashboard:
    build: 
      context: dashboard
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - postgresdb
    ports:
      - "5001:5000"
    environment:
      - IS_DOCKER=Yes
    labels:
      kompose.service.type: LoadBalancer
  recommender:
    build: 
      context: recommender
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - postgresdb
    volumes:
      - ./:/usr/src/app
    ports:
      - "5002:5000"
    environment: 
      PYSPARK_SUBMIT_ARGS: --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.1,org.postgresql:postgresql:42.2.19 --driver-class-path /app/api/postgresql-42.2.19.jar pyspark-shell
  database-api:
    build:
      context: database/api
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgresdb
    volumes:
      - ./:/usr/src/app
    ports:
      - "5003:5000"
  auth:
    build:
      context: auth
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - postgresdb
    volumes:
      - ./:/usr/src/app
    ports:
      - "5004:5000"
  